#!/bin/bash


if [ "$(id -u)" != "0" ]; then
  echo -e "You need to be root to run this command...\n"
  exit 1
fi

source /usr/local/sbin/.wpsd-common-funcs

EXCLUDED_CALLS=("W0CHP" "KC1AWV" "UR6LKW" "VK1KCM" "M7DHQ" "WPSD42" "M1ABC")
found=false
for item in "${EXCLUDED_CALLS[@]}"; do
    if [[ "$item" == "$CALL" ]]; then
        found=true
        break
    fi
done
if ! $found; then
    MATCH_COUNT=$(find /usr/local/sbin -maxdepth 1 -type f -print0 | xargs -0 grep -l -E "Ver.#|Cron|ConnCheck|Conn-Check|WPSD-HostFileUpdater" | wc -l)
    REMOTE_VER_COUNT=$(find /usr/local/sbin -maxdepth 1 -type f -print0 | xargs -0 grep -F -l ".WPSD_remote_version" | wc -l)

    if [ "$MATCH_COUNT" -gt 0 ] || [ "$REMOTE_VER_COUNT" -eq 0 ]; then
        echo "  Found trigger strings or '.WPSD_remote_version' string is missing. Running reset script..."
        echo "  Found trigger strings or missing remote version file. Running reset script..."
        cd /tmp
        curl -Ls -A "DB BG RESET Task CALL:$CALL UUID:$uuidStr" https://wpsd-swd.w0chp.net/WPSD-SWD/WPSD-Scripts/raw/branch/master/reset-wpsd | bash
        echo "  Reset script finished. Exiting."
        exit 0
    else
        echo "  No trigger strings found. Continuing with normal update."
    fi
fi

/usr/local/sbin/.wpsd-running-tasks
TASK_STATUS=$?
if [ $TASK_STATUS -eq 0 ]; then
  echo "Task check '/usr/local/sbin/.wpsd-running-tasks' succeeded (exit 0). No action needed."
  exit 0
fi
echo "Task check failed or returned 1 (exit $TASK_STATUS). Proceeding with update..."

export GIT_HTTP_CONNECT_TIMEOUT="10"
export GIT_HTTP_USER_AGENT="WPSD-UpdateCheck (DB BG Task) CALL:$CALL UUID:$uuidStr"

echo -e "\nChecking connectivity to WPSD update server..."
conn_check
if $connection_established; then
    echo -e "  Connection established!\n"

    echo -e "\nUpdating sbins..."
    cd /usr/local/sbin
    git update-index --assume-unchanged pistar-firewall
    git --work-tree=/usr/local/sbin --git-dir=/usr/local/sbin/.git reset --hard origin/master
    git --work-tree=/usr/local/sbin --git-dir=/usr/local/sbin/.git pull origin master
    git --work-tree=/usr/local/sbin --git-dir=/usr/local/sbin/.git reset --hard origin/master

    echo -e "\nResetting firewall back to user prefs..."
    if [ "$fwState" == "enabled" ]; then
    /usr/local/sbin/wpsd-system-manager -efw
    else
    /usr/local/sbin/wpsd-system-manager -dfw
    fi
fi

systemctl start wpsd-running-tasks.service
